# .github/workflows/deploy.yml
name: Deploy Pages
on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 將目前目錄打包成 artifact
      - uses: actions/upload-pages-artifact@v3
        with:
          path: '.'            # ★ 修正：改掉預設 _site/

      - uses: actions/deploy-pages@v4
        id: deploy
